services:
  backend:
    build: 
      context: ./backend
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    environment:
      - PORT=8000
      - DATABASE_PATH=/app/data/pissgraph.db
      - POLLING_INTERVAL=${POLLING_INTERVAL:-60}
      - CORS_ORIGINS=${FRONTEND_URL:-http://localhost:3000}
      - ENABLE_SEED_ENDPOINT=${ENABLE_SEED_ENDPOINT:-true}
    volumes:
      - pissgraph_data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
      args:
        - VITE_API_BASE_URL=${BACKEND_URL:-http://localhost:8000}
    ports:
      - "${FRONTEND_PORT:-3000}:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  pissgraph_data: